export default function DisclaimerPage() {
  return (
    <main className="mx-auto max-w-3xl space-y-6 px-4 py-8">
      <h1 className="text-3xl font-bold text-ink">Disclaimer</h1>
      <div className="space-y-4 text-sm leading-6 text-slate-700">
        <p>Course Planner is an independent student-created platform and is not affiliated with, endorsed by, or operated by the University of Auckland.</p>
        <h2 className="text-lg font-bold text-ink">Platform Disclaimer</h2>
        <p>Course Planner provides informational tools only and does not provide academic, legal, or professional advice. Students should verify important information using official university sources before making enrolment decisions.</p>
        <h2 className="text-lg font-bold text-ink">Course Information</h2>
        <p>Course information is sourced from publicly available university catalogues and may be incomplete, outdated, or inaccurate. University names and course information are referenced for informational purposes only.</p>
        <h2 className="text-lg font-bold text-ink">Assessment & Exam Data</h2>
        <p>Assessment structures and exam mode data are based on publicly available information and may vary between semesters. Easy A Index and Grade Outlook are independent estimates generated by Course Planner and are not official university performance data.</p>
        <h2 className="text-lg font-bold text-ink">Review Data</h2>
        <p>Student review content displayed on this site is demo data — example content for demonstration purposes only. It is not based on actual student submissions.</p>
      </div>
    </main>
  );
}
